import { MedicalReport, DosageRecommendation } from '../../types/medical';

export class ReportFormatter {
  static generateSummaryText(
    report: MedicalReport,
    recommendation: DosageRecommendation | null,
    condition: string
  ): string {
    const { patientInfo, tests } = report;
    
    let summary = `THYROID FUNCTION ANALYSIS SUMMARY\n`;
    summary += `${'='.repeat(50)}\n\n`;
    
    // Patient Information
    summary += `PATIENT INFORMATION\n`;
    summary += `${'-'.repeat(20)}\n`;
    summary += `Name: ${patientInfo.name || 'Not specified'}\n`;
    summary += `Age: ${patientInfo.age ? `${patientInfo.age} years` : 'Not specified'}\n`;
    summary += `Gender: ${patientInfo.gender || 'Not specified'}\n`;
    if (patientInfo.date) {
      summary += `Report Date: ${patientInfo.date}\n`;
    }
    summary += `\n`;

    // Test Results
    summary += `LABORATORY RESULTS\n`;
    summary += `${'-'.repeat(20)}\n`;
    Object.entries(tests).forEach(([testName, test]) => {
      if (test) {
        summary += `${testName}: ${test.value} ${test.units || ''} `;
        if (test.status) {
          summary += `(${test.status.toUpperCase()})`;
        }
        if (test.refRange) {
          summary += ` [Reference: ${test.refRange.low}-${test.refRange.high}]`;
        }
        summary += `\n`;
      }
    });
    summary += `\n`;

    // Clinical Assessment
    summary += `CLINICAL ASSESSMENT\n`;
    summary += `${'-'.repeat(20)}\n`;
    summary += `Diagnosis: ${condition}\n`;
    
    if (recommendation) {
      summary += `Severity: ${recommendation.severity.charAt(0).toUpperCase() + recommendation.severity.slice(1)}\n\n`;
      
      if (recommendation.dosage > 0) {
        summary += `TREATMENT RECOMMENDATION\n`;
        summary += `${'-'.repeat(25)}\n`;
        summary += `Medication: ${recommendation.medication}\n`;
        summary += `Dosage: ${recommendation.dosage} ${recommendation.unit}\n`;
        summary += `Frequency: ${recommendation.frequency}\n`;
        summary += `Follow-up: ${recommendation.followUpWeeks} weeks\n\n`;
      }
      
      summary += `CLINICAL REASONING\n`;
      summary += `${'-'.repeat(18)}\n`;
      summary += `${recommendation.reasoning}\n\n`;
    }

    summary += `IMPORTANT DISCLAIMER\n`;
    summary += `${'-'.repeat(20)}\n`;
    summary += `This analysis is generated by AI for educational purposes only.\n`;
    summary += `Always consult with qualified healthcare professionals for medical decisions.\n`;
    summary += `Individual patient factors may require different treatment approaches.\n`;

    return summary;
  }

  static formatTestValue(value: number, units?: string | null): string {
    return `${value}${units ? ` ${units}` : ''}`;
  }

  static formatDateForFilename(date?: string | null): string {
    if (date) {
      return date.replace(/\s+/g, '-').toLowerCase();
    }
    return new Date().toISOString().split('T')[0];
  }
}